name: NuGet-publish

on:
  push:
    branches:
      - main
    paths:
      - 'ClassLibrary1/SampleNuget.csproj'

  # 手動実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # ビルド
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish NuGet
        run: dotnet nuget push ClassLibrary1/bin/Release/SampleNuget.*.nupkg --source "github" --api-key ${{secrets.GITHUB_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
