name: NuGet-publish

on:
  push:
    branches:
      - main
    paths:
      - 'ClassLibrary1/SampleNuget.csproj'

  # 手動実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Pack NuGet Package
        run: dotnet pack ClassLibrary1/SampleNuget.csproj -c Release -o ./dist

      - name: Publish NuGet
        run: dotnet nuget push dist/*.nupkg --source https://nuget.pkg.github.com/ks-kentem/index.json --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
